.PHONY: create_prime create_sleep invoke_sleep invoke_prime

create_prime:
	./create_isPrime_function.sh prime 100

create_sleep:
	./create_sleep_function.sh sleep 100

invoke_sleep:
	./default_invoke_function.sh sleep 4

invoke_prime:
	./default_invoke_function.sh prime 10
